SELECT DISTINCT CITY FROM STATION WHERE NOT SUBSTR(CITY,1,1) IN ('a','e','i','o','u','A','E','I','O','U') OR NOT SUBSTR(CITY,LENGTH(CITY),LENGTH(CITY)+1) IN ('a','e','i','o','u','A','E','I','O','U');
/*

HERE WE HAVE TO USE 'OR' INSED OF 'AND' BECAUSE IF EITHER ONE OR BOTH HAS VOWEL IS OUT
*/
