/*
quary the name from student table where marks is greater than 75 order by the last 3 word of the string 
with right(string,3) and sort them in assending order AND ALSO BY ID IN CASE THERE ARE SAME LAST THREE CHARACTER
SELECT NAME FROM STUDENTS WHERE MARKS > 75 ORDER BY RIGHT(NAME, 3), ID ASC;
CAUSE IF YOU ORDER BY TWO PARAMETER IF IN CASE TWO DATA SAME IT WILL SORTED BY THE SECOND PARAMETER
IT CAN BE DONE BY SUBSTR ALSO
*/
/*
SELECT NAME FROM STUDENTS WHERE MARKS > 75 ORDER BY RIGHT(NAME,3),ID;
RIGHT() FUNCTION RETURNS THE VALUE AT THE RIGHT
*/
SELECT NAME FROM STUDENTS WHERE MARKS > 75 ORDER BY SUBSTR(NAME,LENGTH(NAME)-2,LENGTH(NAME)),ID;
SELECT NAME FROM STUDENTS WHERE MARKS > 75 ORDER BY RIGHT(NAME,3),ID ASC;
