/*
Enter your query here.
THE CODE IS TRICKY LET ME EXPLAIN
THE QUESTION IS 
Query the Western Longitude (LONG_W) for the largest Northern Latitude (LAT_N) in STATION that is less than 137.2345.
SELECT THE LONG_W FROM THE MAXIMUM VALUE OF THE LIST ,THE LIST WHICH IS LESS THAN 137.2345;
WE NEED A SUB QUARY
*/
SELECT ROUND(LONG_W,4) FROM STATION WHERE LAT_N=(SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345);
