/*
Given the CITY and COUNTRY tables, query the sum of the populations of all cities where the CONTINENT is 'Asia'
OK THERE IS CITY TABLE AND FROM  CITY(CITY TABLE) WE SUM THE POPULATION BUT THAT HAVE TO BE IN ASIA
SO WE FETCHED ALL CONTRY CODE IN ASIA AND GIVE IT TO THE FIRST QUARY
*/
SELECT SUM(CITY.POPULATION) FROM CITY WHERE CITY.COUNTRYCODE IN(SELECT CODE FROM COUNTRY WHERE CONTINENT='ASIA');
