/*
Enter your query here.
READ CAREFULLY YOU HAVE TO USE A SUB QUARY
select round(LONG_W,4) from STATION where LAT_N=(select min(LAT_N) from STATION where LAT_N>38.7780);

*/
SELECT ROUND(LONG_W,4) FROM STATION WHERE LAT_N =(SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.7780);

